version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow_server:
    build: .
    container_name: mlflow_server
    depends_on:
     - postgres
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow_db
      --default-artifact-root /app/mlflow/artifacts
    volumes:
      - mlflow_artifacts:/app/mlflow/artifacts

volumes:
  postgres_data:
  mlflow_artifacts:
