# Use an official Python runtime as a parent image
FROM ghcr.io/mlflow/mlflow:latest

# Set the working directory in the container
WORKDIR /app
USER root

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir -U mlflow psycopg2-binary 

# Copy the current directory contents into the container at /app
COPY . .

# Expose port 5000 for the MLflow server
EXPOSE 5000

# Define environment variable
ENV NAME mlflow_server