version: "3.8"

services:
  postgres:
    image: postgres

    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow_server:
    build: .
    container_name: mlflow_server
    depends_on:
     - postgres
    ports:
      - "8080:8080"
    volumes:
      - mlflow_artifacts:/app/mlflow/artifacts
      
volumes:
  postgres_data:
  mlflow_artifacts:
