name: CI pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
      
    defaults:
        run:
            working-directory: CI-CD/todo-app
    
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14'
      - run : npm ci
      - run : npm test
      - run : npm run build
